// ============================================================================
// Jenkins Pipeline - Generic Project
// ============================================================================
// This pipeline provides basic CI/CD for any project type.
// It runs Makefile targets if available, or basic shell commands.
//
// Requirements:
//   - Jenkins with Pipeline and Git plugins
//
// Generated by: projenitor jenkins setup
// ============================================================================

pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
        ansiColor('xterm')
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm

                script {
                    env.GIT_COMMIT_SHORT = sh(
                        script: 'git rev-parse --short HEAD',
                        returnStdout: true
                    ).trim()

                    env.GIT_BRANCH_NAME = sh(
                        script: 'git rev-parse --abbrev-ref HEAD',
                        returnStdout: true
                    ).trim()
                }

                echo "Building commit ${env.GIT_COMMIT_SHORT} on branch ${env.GIT_BRANCH_NAME}"
            }
        }

        stage('Setup') {
            steps {
                sh '''
                    echo "Project structure:"
                    ls -la

                    echo ""
                    echo "Available Makefile targets:"
                    if [ -f "Makefile" ]; then
                        grep -E "^[a-zA-Z_-]+:" Makefile | cut -d: -f1 | head -20 || true
                    else
                        echo "No Makefile found"
                    fi
                '''
            }
        }

        stage('Install') {
            steps {
                sh '''
                    echo "Running install/setup..."

                    if [ -f "Makefile" ]; then
                        if make -n install >/dev/null 2>&1; then
                            make install
                        elif make -n setup >/dev/null 2>&1; then
                            make setup
                        elif make -n deps >/dev/null 2>&1; then
                            make deps
                        else
                            echo "No install/setup/deps target in Makefile"
                        fi
                    else
                        echo "No Makefile, skipping install"
                    fi
                '''
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    echo "Running lint..."

                    if [ -f "Makefile" ]; then
                        if make -n lint >/dev/null 2>&1; then
                            make lint || true
                        elif make -n check >/dev/null 2>&1; then
                            make check || true
                        else
                            echo "No lint/check target in Makefile"
                        fi
                    else
                        echo "No Makefile, skipping lint"
                    fi
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    echo "Running tests..."

                    if [ -f "Makefile" ]; then
                        if make -n test >/dev/null 2>&1; then
                            make test || true
                        elif make -n tests >/dev/null 2>&1; then
                            make tests || true
                        else
                            echo "No test/tests target in Makefile"
                        fi
                    else
                        echo "No Makefile, skipping tests"
                    fi
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    echo "Running build..."

                    if [ -f "Makefile" ]; then
                        if make -n build >/dev/null 2>&1; then
                            make build
                        elif make -n all >/dev/null 2>&1; then
                            make all
                        else
                            echo "No build/all target in Makefile"
                        fi
                    else
                        echo "No Makefile, skipping build"
                    fi

                    # Show any build artifacts
                    for dir in dist build out bin; do
                        if [ -d "$dir" ]; then
                            echo ""
                            echo "Build artifacts in $dir/:"
                            ls -la "$dir/"
                        fi
                    done
                '''
            }

            post {
                success {
                    archiveArtifacts artifacts: 'dist/**/*,build/**/*,out/**/*,bin/**/*', allowEmptyArchive: true, fingerprint: true
                }
            }
        }
    }

    post {
        always {
            cleanWs(
                cleanWhenNotBuilt: false,
                deleteDirs: true,
                disableDeferredWipeout: true,
                notFailBuild: true
            )
        }

        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
