// ============================================================================
// Jenkins Pipeline - yad
// ============================================================================
// Generated by: projenitor
// Language: shell
// ============================================================================

pipeline {
    agent any

    environment {
        CI = 'true'
        
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
        ansiColor('xterm')
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                script {
                    env.GIT_COMMIT_SHORT = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    env.GIT_BRANCH_NAME = sh(script: 'git rev-parse --abbrev-ref HEAD', returnStdout: true).trim()
                }
                echo "Building ${project_name} - commit ${env.GIT_COMMIT_SHORT} on branch ${env.GIT_BRANCH_NAME}"
            }
        }

        stage('Install Dependencies') {
            steps {
                
                echo "No specific install steps for shell"
                
            }
        }

        stage('Lint') {
            parallel {
                stage('Main Lint') {
                    steps {
                        
                        echo "Skipping lint for shell"
                        
                    }
                }
                
            }
        }

        stage('Test') {
            steps {
                
                echo "Skipping tests for shell"
                
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: '**/junit.xml'
                }
            }
        }
    }

    post {
        always {
            cleanWs(
                cleanWhenNotBuilt: false,
                deleteDirs: true,
                disableDeferredWipeout: true,
                notFailBuild: true,
                patterns: [
                    [pattern: '.venv/**', type: 'INCLUDE'],
                    [pattern: 'node_modules/**', type: 'INCLUDE'],
                    [pattern: '.uv-cache/**', type: 'INCLUDE'],
                    [pattern: '__pycache__/**', type: 'INCLUDE']
                ]
            )
        }

        success {
            echo 'Pipeline completed successfully!'

            // Auto-merge PR on success (only for PR builds in multibranch pipeline)
            script {
                if (env.CHANGE_ID) {
                    echo "Auto-merging PR #${env.CHANGE_ID}..."
                    withCredentials([usernamePassword(credentialsId: 'github-pat', usernameVariable: 'GH_USER', passwordVariable: 'GH_TOKEN')]) {
                        sh '''#!/bin/bash
                            set +e  # Don't exit on error

                            # Auto-detect repo owner and name from git remote
                            REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
                            if [ -z "$REMOTE_URL" ]; then
                                echo "No origin remote found, skipping auto-merge"
                                exit 0
                            fi

                            # Parse owner/repo from URL (handles both HTTPS and SSH)
                            REPO_OWNER=$(echo "$REMOTE_URL" | sed -E 's#.*[:/]([^/]+)/([^/]+)(\\.git)?$#\\1#')
                            REPO_NAME=$(echo "$REMOTE_URL" | sed -E 's#.*[:/]([^/]+)/([^/]+)(\\.git)?$#\\2#' | sed 's/\\.git$//')

                            echo "Detected repository: ${REPO_OWNER}/${REPO_NAME}"

                            # Get PR info and check if draft
                            PR_INFO=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
                                "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${CHANGE_ID}")
                            IS_DRAFT=$(echo "$PR_INFO" | grep -E '"draft"\\s*:\\s*true' || echo "")
                            if [ -n "$IS_DRAFT" ]; then
                                echo "PR is a draft, converting to ready..."
                                PR_NODE_ID=$(echo "$PR_INFO" | grep -oE '"node_id"\\s*:\\s*"[^"]+"' | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
                                if [ -n "$PR_NODE_ID" ]; then
                                    GRAPHQL_JSON=$(printf '{"query": "mutation { markPullRequestReadyForReview(input: {pullRequestId: \\\\"%s\\\\"}) { pullRequest { isDraft } } }"}' "$PR_NODE_ID")
                                    curl -s -X POST -H "Authorization: bearer $GH_TOKEN" -H "Content-Type: application/json" "https://api.github.com/graphql" -d "$GRAPHQL_JSON"
                                fi
                                sleep 2
                            fi

                            # Merge the PR with squash using GitHub API
                            MERGE_RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/merge_response.json \
                                -X PUT \
                                -H "Authorization: token $GH_TOKEN" \
                                -H "Accept: application/vnd.github.v3+json" \
                                "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${CHANGE_ID}/merge" \
                                -d '{"merge_method":"squash"}')

                            if [ "$MERGE_RESPONSE" = "200" ]; then
                                echo "PR #${CHANGE_ID} merged successfully!"

                                # Delete the branch
                                BRANCH_NAME=$(curl -s \
                                    -H "Authorization: token $GH_TOKEN" \
                                    -H "Accept: application/vnd.github.v3+json" \
                                    "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${CHANGE_ID}" \
                                    | grep -o '"ref": "[^"]*"' | head -1 | cut -d'"' -f4)

                                if [ -n "$BRANCH_NAME" ]; then
                                    curl -s -X DELETE \
                                        -H "Authorization: token $GH_TOKEN" \
                                        -H "Accept: application/vnd.github.v3+json" \
                                        "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/git/refs/heads/${BRANCH_NAME}" \
                                        && echo "Branch ${BRANCH_NAME} deleted"
                                fi

                                # Update main worktree after successful merge
                                if [ -f "scripts/jenkins/update-main-worktree.sh" ]; then
                                    echo "Updating main worktree..."
                                    chmod +x scripts/jenkins/update-main-worktree.sh
                                    ./scripts/jenkins/update-main-worktree.sh "$(pwd)" main || echo "Worktree update failed (non-critical)"
                                fi
                            else
                                echo "Auto-merge failed (HTTP $MERGE_RESPONSE)"
                                cat /tmp/merge_response.json 2>/dev/null || true
                            fi
                        '''
                    }
                }
            }
        }

        unstable {
            echo 'Pipeline unstable (tests passed but coverage/quality issues)'

            // Auto-merge on unstable if tests passed (coverage threshold shouldn't block merge)
            script {
                if (env.CHANGE_ID) {
                    echo "Auto-merging PR #${env.CHANGE_ID} (unstable but tests passed)..."
                    withCredentials([usernamePassword(credentialsId: 'github-pat', usernameVariable: 'GH_USER', passwordVariable: 'GH_TOKEN')]) {
                        sh '''#!/bin/bash
                            set +e  # Don't exit on error

                            # Auto-detect repo owner and name from git remote
                            REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
                            if [ -z "$REMOTE_URL" ]; then
                                echo "No origin remote found, skipping auto-merge"
                                exit 0
                            fi

                            # Parse owner/repo from URL (handles both HTTPS and SSH)
                            REPO_OWNER=$(echo "$REMOTE_URL" | sed -E 's#.*[:/]([^/]+)/([^/]+)(\\.git)?$#\\1#')
                            REPO_NAME=$(echo "$REMOTE_URL" | sed -E 's#.*[:/]([^/]+)/([^/]+)(\\.git)?$#\\2#' | sed 's/\\.git$//')

                            echo "Detected repository: ${REPO_OWNER}/${REPO_NAME}"

                            # Get PR info and check if draft
                            PR_INFO=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
                                "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${CHANGE_ID}")
                            IS_DRAFT=$(echo "$PR_INFO" | grep -E '"draft"\\s*:\\s*true' || echo "")
                            if [ -n "$IS_DRAFT" ]; then
                                echo "PR is a draft, converting to ready..."
                                PR_NODE_ID=$(echo "$PR_INFO" | grep -oE '"node_id"\\s*:\\s*"[^"]+"' | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/')
                                if [ -n "$PR_NODE_ID" ]; then
                                    GRAPHQL_JSON=$(printf '{"query": "mutation { markPullRequestReadyForReview(input: {pullRequestId: \\\\"%s\\\\"}) { pullRequest { isDraft } } }"}' "$PR_NODE_ID")
                                    curl -s -X POST -H "Authorization: bearer $GH_TOKEN" -H "Content-Type: application/json" "https://api.github.com/graphql" -d "$GRAPHQL_JSON"
                                fi
                                sleep 2
                            fi

                            # Merge the PR with squash using GitHub API
                            MERGE_RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/merge_response.json \
                                -X PUT \
                                -H "Authorization: token $GH_TOKEN" \
                                -H "Accept: application/vnd.github.v3+json" \
                                "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${CHANGE_ID}/merge" \
                                -d '{"merge_method":"squash"}')

                            if [ "$MERGE_RESPONSE" = "200" ]; then
                                echo "PR #${CHANGE_ID} merged successfully!"

                                # Delete the branch
                                BRANCH_NAME=$(curl -s \
                                    -H "Authorization: token $GH_TOKEN" \
                                    -H "Accept: application/vnd.github.v3+json" \
                                    "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${CHANGE_ID}" \
                                    | grep -o '"ref": "[^"]*"' | head -1 | cut -d'"' -f4)

                                if [ -n "$BRANCH_NAME" ]; then
                                    curl -s -X DELETE \
                                        -H "Authorization: token $GH_TOKEN" \
                                        -H "Accept: application/vnd.github.v3+json" \
                                        "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/git/refs/heads/${BRANCH_NAME}" \
                                        && echo "Branch ${BRANCH_NAME} deleted"
                                fi

                                # Update main worktree after successful merge
                                if [ -f "scripts/jenkins/update-main-worktree.sh" ]; then
                                    echo "Updating main worktree..."
                                    chmod +x scripts/jenkins/update-main-worktree.sh
                                    ./scripts/jenkins/update-main-worktree.sh "$(pwd)" main || echo "Worktree update failed (non-critical)"
                                fi
                            else
                                echo "Auto-merge failed (HTTP $MERGE_RESPONSE)"
                                cat /tmp/merge_response.json 2>/dev/null || true
                            fi
                        '''
                    }
                }
            }
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}